FROM rocm/dev-ubuntu-24.04:latest AS build

WORKDIR /src

RUN apt update && \
apt install -y libclfft-dev git python3-pip python3-dev && \
pip install --break-system-packages build setuptools wheel cython

COPY . .

RUN python3 -m build --wheel

RUN pip wheel -w dist --no-deps --no-use-pep517 gpyfft@git+https://github.com/geggo/gpyfft@v0.8.0

FROM rocm/dev-ubuntu-24.04:latest

RUN apt update && apt install -y libclfft2 python3-pip

COPY --from=build /src/dist/*.whl /opt/

RUN PFWHL_FILE=$(find /opt -name "powerfit*.whl" | head -n 1) && \
    GFWHL_FILE=$(find /opt -name "gpyfft*.whl" | head -n 1) && \
    pip install --break-system-packages "${PFWHL_FILE}[opencl]" "${GFWHL_FILE}"

ENTRYPOINT [ "powerfit" ]
