FROM rocm/dev-ubuntu-24.04:latest AS build

WORKDIR /src

RUN pip install --break-system-packages build setuptools wheel cython

COPY . .

RUN python3 -m build --wheel

FROM rocm/dev-ubuntu-24.04:latest

RUN apt update && apt install -y ocl-icd-opencl-dev ocl-icd-libopencl1 python3-pip

COPY --from=build /src/dist/*.whl /opt/

RUN PFWHL_FILE=$(find /opt -name "powerfit*.whl" | head -n 1) && \
    pip install --break-system-packages "${PFWHL_FILE}[opencl]"

ENTRYPOINT [ "powerfit" ]
