FROM python:3.13 AS build

WORKDIR /src

RUN pip install build

COPY . .

RUN python -m build --wheel

FROM python:3.13-slim

COPY --from=build /src/dist/*.whl /opt/

RUN WHL_FILE=$(find /opt -name "*.whl" | head -n 1) && \
    pip install "${WHL_FILE}[fftw]"

ENTRYPOINT [ "powerfit" ]
