name: ci

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: install python deps from pypi
        run: pip install -e .[dev,pocl]

      - name: install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libclfft-dev

      - name: install gpyfft
        run: |
          pip install -U cython wheel setuptools
          pip install --no-use-pep517 gpyfft@git+https://github.com/geggo/gpyfft@v0.8.0

      - name: OpenCL platform and device test
        run: python -c 'import pyopencl as cl;import pyopencl.array as cl_array;from gpyfft import GpyFFT; ps=cl.get_platforms();print(ps);print(ps[0].get_devices())'

      - name: test
        run: >-
          pytest --cov --cov-report xml:coverage.xml -vvv

      - uses: codacy/codacy-coverage-reporter-action@v1
        if: >-
          ${{ github.event_name != 'pull_request' ||
          github.event.pull_request.head.repo.full_name == github.repository }}
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./coverage.xml
