name: ci

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: build deps
        run: pip install numpy setuptools wheel

      - name: build
        run: python setup.py build_ext --inplace

      - name: install
        run: pip install -e . --no-use-pep517

      - name: test deps
        run: pip install pytest

      - name: test
        run: pytest
